language: php
php:
- 5.5
- 5.5.9
- 5.6
- 7.0
- hhvm
matrix:
  allow_failures:
  - php: hhvm
install: composer install --dev
script:
- bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
after_script:
- bin/test-reporter
notifications:
  slack:
    secure: dk54BkrbMUOHnZCmxKG+RzJDlZ8QeTuQtntz+1Ax3y4CamWfEil+XvTGE6qmg0CALM2ZGij8edvrLkuyQFYA79FX5pwz/djzqQpXKxqvDlzP0JL2NnDDkvv6/VZXm+K7nVWlj093XVf+B+/EZ82RE8MAFOoS+pNKmVOanshQeQ0DKRtIOzyWvoTizf+s5/iuXOAuuo82YBxZvuKqCVvCGg5kx666cG0YR1MEcoxruJoC73vcs/1NtuBUPPRDd5lGUx7B3H+CSOk8Ww7IlvrXUXMza+ht+mc2ZZDbNNZxMn1noX7aqTqCH81jiqkN7fSJ6B3DbgAWyq7If+/sXDLwWNrHJauvzSs8wKCq5X/SGezuGe40N3xF8TtJn8hlCvPUyTJ+dOIIgd7ENQZCyt9x+SdXrczhdRZmHhW9Xv+oQvgLy0AyEAVhYSmkfDiha8FLYn2fF+t8LIio9Ntc2AfZsjxSZW/NuAKDzFUryF/5j6pkw1b0VyemVPeRXYecc/QMzG1aWHSLdyuLNjO/wpIii8Ik5gyELWrsrKOvEctbN3WFb/Ijo7dFY6nyHJFqYy/fq50E8k7Obym+7nm9tCzqWZSgh5yNEOpFQQje5UHdYEgPLYa7+tnEpZUKzMD1ScVjaLMfbryNgQH8av47DOt10W1h3g0msjY4R4iZBGoJjZw=
